### PR TITLE
Fix snitch immune players toggling levers

### PR DESCRIPTION
**Pull request by squareblob**

### CODE REVIEW

**Comment by wingzero54** [comment]
If I understand this correctly, it's so that only players who will be logged by the snitch will cause the lever to be toggled, leading to some other redstone action? To prevent snitch immune players from triggering the trap/switch/ etc?

**Comment by squareblob** [comment]
Correct, this is how JukeAlert was [supposed to behave](https://github.com/DevotedMC/JukeAlert/blob/80980729c0faaba6e0128e94018c25cadedd1ad4/src/main/java/com/untamedears/JukeAlert/listener/JukeAlertListener.java#L885-L891) but it seems to have been broken for some time on Classics

**Comment by Convoy20** [comment]
Check if this fixes the issue for group owners. On civrealms as a group owner I could not snitch toggle immune.

**Comment by squareblob** [comment]
> Check if this fixes the issue for group owners. On civrealms as a group owner I could not snitch toggle immune.

This does not seem to be an issue anymore

**Comment by squareblob** [comment]
Bump

**Pull request merged**
