### PR TITLE
reverse jalist somewhere else

### PR DESCRIPTION
**Pull request by TheOrangeWizard**

### CODE REVIEW

**Review by okx-code — COMMENTED** [review]
Would recommend using [Comparator.comparingLong](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#comparingLong-java.util.function.ToLongFunction-) instead

**Comment by Protonull** [comment]
> Would recommend using [Comparator.comparingLong](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#comparingLong-java.util.function.ToLongFunction-) instead

Screenshot 2021-03-01 at 11 33 17

Why? It calls `Long.compare()` anyway.. it's just adding another method call on top of that. And considering how the cull timers are stored on objects that may or may not exist and that java doesn't have optional chaining, I don't really see how the current sorting solution can be improved.

**Comment by okx-code** [comment]
It lets you write cleaner code since you only need to write the key extractor function once, not twice

**Comment by Protonull** [comment]
> It lets you write cleaner code since you only need to write the key extractor function once, not twice

Gotta contest that. These are the two sorting functions side by side:

Screenshot 2021-03-01 at 17 41 54

The first looks longer and more verbose, but that's because I went out of the way to store those values as variables for readability. I could've just as easily inlined everything into the parameters of `Long.compare()`. I've actually gotta agree with one of Maxopoly's complaints about the over use of lambdas here, as with the case of the second sort function, it's not immediately obvious what it's comparison nor how it's comparing it, nor how you'd modify that comparison. Indeed this PR's change isn't a `Collections.reverse()`, which would add unnecessary computation since a sorting is already coded, but a mere swapping of parameters within the sort function.

I'm, of course, not suggesting that `Comparator.comparingLong()` is always bad or something, but since the appender data cannot be easily collapsed into a lambda reference, [like so](https://github.com/CivClassic/NameLayer/blob/71fe7aa910982f0f52b09c9a2b5016849a860970/namelayer-spigot/src/main/java/vg/civcraft/mc/namelayer/gui/PermissionManageGUI.java#L118), it's simply a worser option.

**Comment by TheOrangeWizard** [comment]
i don't understand what any of this means so i'm going to leave it as is

**Pull request merged**
